### PR TITLE
Copy scope id when binding to IPv6 Link-Local address

### LINKED ISSUE #2696: bind_interface doesn't work, mosquitto only binds to localhost
mosquitto-2.0.15 on Gentoo Lignux here. `strace` doesn't tell any hints on why doesn't it work. `listener` works but is unsuitable for dynamic IP addresses.
```
∞ grep -Ev '^#|^$' /etc/mosquitto/mosquitto.conf 
persistent_client_expiration 1y
bind_interface eth2
autosave_interval 1800
persistence true
persistence_file mosquitto.db
persistence_location /var/lib/mosquitto/
log_dest syslog
log_type information
allow_anonymous true
```

### PR DESCRIPTION
**Pull request by ThymoNL**
Thank you for contributing your time to the Mosquitto project!

Before you go any further, please note that we cannot accept contributions if
you haven't signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php).
If you aren't able to do that, or just don't want to, please describe your bug
fix/feature change in an issue. For simple bug fixes it is can be just as easy
for us to be told about the problem and then go fix it directly.

Then please check the following list of things we ask for in your pull request:

- [x] Have you signed the [Eclipse Contributor Agreement](https://www.eclipse.org/legal/ECA.php), using the same email address as you used in your commits?
- [x] Do each of your commits have a "Signed-off-by" line, with the correct email address? Use "git commit -s" to generate this line for you.
- [x] If you are contributing a bugfix, is your work based off the fixes branch?
- [x] Have you added an explanation of what your changes do and why you'd like us to include them?
- [x] Have you successfully run `make test` with your changes locally?

-----

Configuring a listener with bind_interface on an interface with an ipv6 link-local address causes Mosquitto to exit with "Error: invalid argument". This happens due to the the IPv6 scope ID not being copied to the returned addrinfo struct when resolving interfaces matching `bind_interface`.

This PR adds a commit that also copies the sin6_scope_id when a matching interface is found.

Fixes #2696

### CODE REVIEW

**Comment by ThymoNL** [comment]
@ralight May I gently bump this your way?  Hoping you can take a look at this bugfix. 🙂

File: src/net.c [hunk 1]
```diff
@@ -673,6 +673,9 @@ static int net__bind_interface(struct mosquitto__listener *listener, struct addr
 						memcpy(&((struct sockaddr_in6 *)rp->ai_addr)->sin6_addr,
 								&((struct sockaddr_in6 *)ifa->ifa_addr)->sin6_addr,
 								sizeof(struct in6_addr));
+
+						((struct sockaddr_in6 *)rp->ai_addr)->sin6_scope_id = ((struct sockaddr_in6 *)ifa->ifa_addr)->sin6_scope_id;
```
Comment (ralight) [inline src/net.c:677]: Can you explain why the memcpy call in line 673 isn't sufficient to copy this value already?

Comment (ThymoNL) [reply src/net.c:677]: Is your question why only copying the in6_addr is not enough? That's because for link-local addresses they are only valid for a specific interface, you can specify which interface the address belongs to with the scope id.

If your question is why I didn't group everything into a single memcpy call. That was for readability.

**Comment by ThymoNL** [comment]
@ralight Can I do anything else to answer your questions in order to get this merged? :)

**Comment by ThymoNL** [comment]
@ralight friendly reminder 🙂

**Comment by ralight** [comment]
@ThymoNL Thanks for the reminder. I would be happy to merge this, however I'd be much happier if there was a test to check the link local case. Any ideas on adding one?

**Comment by ralight** [comment]
Having looked into this a bit more, I think it's going to be impractical to write a general test for it.

The github runners do get a link local address:

```
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 60:45:bd:4a:dd:40 brd ff:ff:ff:ff:ff:ff
    inet 10.1.0.23/16 metric 100 brd 10.1.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::6245:bdff:fe4a:dd40/64 scope link 
       valid_lft forever preferred_lft forever
```

However in other places, like my home, I get other non-link local IPv6 addresses and the bug does not manifest  there in the same way.

**Comment by ThymoNL** [comment]
Yeah, I remember looking at this back then and not finding a trivial way to write a test either. Thanks for merging!
